language: php
php:
  - 5.5
  - 5.4
before_install:
  - composer self-update				# Update Composer to latest version
install:
  - composer install					# Install dependencies
before_script:
  - vendor/bin/codecept build			# Initialise Codeception test environment
script: vendor/bin/codecept run unit	# Run tests!
branches:
  only:
    - master
    - develop
